name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Soal01.java
      id: soal01-java
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Soal01.java
        setup-command: ''
        command: gradle test
        timeout: 10
        max-score: 50
    - name: Soal02.java
      id: soal02-java
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Soal02.java
        setup-command: ''
        command: gradle test
        timeout: 10
        max-score: 50
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SOAL01-JAVA_RESULTS: "${{steps.soal01-java.outputs.result}}"
        SOAL02-JAVA_RESULTS: "${{steps.soal02-java.outputs.result}}"
      with:
        runners: soal01-java,soal02-java
