name: Autograding Java

on: [push, pull_request]

jobs:
  build:
    name: Run Java Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile Code
        run: javac -d out src/main/java/latihan1.java src/test/java/Latihan1Test.java

      - name: Run Tests
        run: |
          cd out
          java org.junit.platform.console.ConsoleLauncher --class-path . --scan-class-path
